### PR TITLE
feat: add nft details page and new hook

### LINKED ISSUE #2: [Feat]: Create NFT Details page
when NFT is click
image

the NFT details or buy page will show 
image

It doesn't have to be completed

### PR DESCRIPTION
**Pull request by AbhinavMV**
## Related Issue

- Information about the related issue

Closes: # 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |
 
## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

Closes #2 

image

### CODE REVIEW

**Comment by vinzvinci** [comment]
The package-lock.json conflicting with yarn.lock, that's why it error.

**Review by vinzvinci — APPROVED** [review]
LGTM! I also check this locally and it works well! Thank you for your contributions! 

Sorry for an error recently, just fixed now!

**Comment by vinzvinci** [comment]
Weird, it failed again after submitting review 👀

**Comment by AbhinavMV** [comment]
Looks like something is wrong with pipeline, I have added ts ignore for now since everything is running.

Also in pipeline still yarn is being used that needs to be fixed too.

**Comment by vinzvinci** [comment]
this is the error showing image

**Review by vinzvinci — APPROVED** [review]
LGTM!

**Comment by vinzvinci** [comment]
Deployment is another issue. This can be merge now!

**Pull request merged**
